apiVersion: v1
kind: Endpoints
metadata:
  name: mysqlagent
subsets:
  - addresses:
    - ip: ${MYSQL_ADDR} 
    ports:
    - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysqlagent
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
