apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol-deployment
  labels:
    app: otelcol-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol-deployment
  template:
    metadata:
      labels:
        app: otelcol-deployment
    spec:
      volumes:
      - name: file-storage
        emptyDir: {}
      - name: file-exporter
        emptyDir: {}
      containers:
      - name: otelcol-deployment
        image: roychshao/otelcol-deployment
        command: ["/app/custom-otelcol"]
        args: ["--config=/app/config.yaml"]
        ports:
        - containerPort: 4317
        volumeMounts:
        - name: file-storage
          mountPath: /var/lib/otelcol
        - name: file-exporter
          mountPath: /tmp/otelcol/file_exporter
      - name: socket-sidecar
        image: roychshao/sunbird-socketsidecar
        command: ["node"]
        args: ["/app/index.js"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: file-exporter
          mountPath: /tmp/otelcol/file_exporter
---

apiVersion: v1
kind: Service
metadata:
  name: otelcol-deployment-service
spec:
  selector:
    app: otelcol-deployment
  type: LoadBalancer
  ports:
    - name: otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30005
    - name: socket
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30006
