apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otelcol-daemonset
  labels:
    app: otelcol-daemonset
spec:
  selector:
    matchLabels:
      app: otelcol-daemonset
  template:
    metadata:
      labels:
        app: otelcol-daemonset
    spec:
      volumes:
      - name: file-storage
        emptyDir: {}
      - name: file-exporter
      containers:
      - name: otelcol-daemonset
        image: roychshao/otelcol-daemonset
        command: ["/app/custom-otelcol"]
        args: ["--config=/app/config.yaml"]
        ports:
        - containerPort: 4317
        volumeMounts:
        - name: file-storage
          mountPath: /var/lib/otelcol
        - name: file-exporter
          mountPath: /tmp/otelcol/file_exporter
      - name: socket-sidecar
        image: roychshao/sunbird-socketsidecar
        command: ["node"]
        args: ["/app/index.js"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: file-exporter
          mountPath: /tmp/otelcol/file_exporter


---

apiVersion: v1
kind: Service
metadata:
  name: otelcol-daemonset-service
spec:
  selector:
    app: otelcol-daemonset
  type: LoadBalancer
  ports:
    - name: otelcol
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30007
    - name: socket
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
