apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-configmap
data:
  # database_url: jdbc:mysql://mysqlagent:3306/jpetstore?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  database_url: ${MYSQL_URL}
  database_username: ${MYSQL_USERNAME}
  database_password: ${MYSQL_PASSWORD}
