receivers:
  otlp/local: # local
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otlp/remote: # remote
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690
      http:
        endpoint: 0.0.0.0:55691

exporters:

  otlp: # jaeger
    endpoint: localhost:6000
    tls:
      insecure: true
  file/localTraces:
    path: ./../localTelemetry/traces.json
  file/localMetrics:
    path: ./../localTelemetry/metrics.json
  file/localLogs:
    path: ./../localTelemetry/logs.json
  file/remoteTraces:
    path: ./../remoteTelemetry/traces.json
  file/remoteMetrics:
    path: ./../remoteTelemetry/metrics.json
  file/remoteLogs:
    path: ./../remoteTelemetry/logs.json

processors:
  batch:

service:
  pipelines:
    # local telemetry pipeline
    traces/local:
      receivers: [otlp/local]
      processors: [batch]
      exporters: [otlp, file/localTraces] 
    metrics/local:
      receivers: [otlp/local]
      processors: [batch]
      exporters: [otlp, file/localMetrics]
    logs/local:
      receivers: [otlp/local]
      processors: [batch]
      exporters: [otlp, file/localLogs]
    # remote telemetry pipeline
    traces/remote:
      receivers: [otlp/remote]
      processors: [batch]
      exporters: [otlp, file/remoteTraces] 
    metrics/remote:
      receivers: [otlp/remote]
      processors: [batch]
      exporters: [otlp, file/remoteMetrics]
    logs/remote:
      receivers: [otlp/remote]
      processors: [batch]
      exporters: [otlp, file/remoteLogs]
