receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690
      http:
        endpoint: 0.0.0.0:55691
  otlpjsonfile:
    include:
      - "../../pulling-server/receivedData/*.json"

exporters:
  loki:
    endpoint: "http://localhost:3100/loki-amd64/api/v1/push"

  loki/2:
    endpoint: "http://localhost:3100/loki-arm64/api/v1/push"

  prometheus:
    endpoint: localhost:9404
    resource_to_telemetry_conversion:
      enabled: true
  
  prometheus/2:
    endpoint: localhost:9405
    resource_to_telemetry_conversion:
      enabled: true

  otlp: # jaeger
    endpoint: localhost:6000
    tls:
      insecure: true
  
  file/traces-amd64:
    path: ./../localTelemetry/traces.json
  file/metrics-amd64:
    path: ./../localTelemetry/metrics.json
  file/logs-amd64:
    path: ./../localTelemetry/logs.json
  file/traces-arm64:
    path: ./../remoteTelemetry/traces.json
  file/metrics-arm64:
    path: ./../remoteTelemetry/metrics.json
  file/logs-arm64:
    path: ./../remoteTelemetry/logs.json


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, file/traces-amd64]
    traces/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [otlp, file/traces-arm64]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, file/metrics-amd64]
    metrics/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [prometheus/2, file/metrics-arm64]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, file/logs-amd64]
    logs/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [loki/2, file/logs-arm64]

