receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:

  otlp: # jaeger
    endpoint: host:6000
    tls:
      insecure: true
  file/Traces:
    path: ./../localTelemetry/traces.json
  file/Metrics:
    path: ./../localTelemetry/metrics.json
  file/Logs:
    path: ./../localTelemetry/logs.json

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, file/Traces] 
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, file/Metrics]
    logs/:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, file/Logs]
