receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"

  prometheus:
    endpoint: localhost:9404
    resource_to_telemetry_conversion:
      enabled: true

  file:
    path: "./telemetry.json"

  otlp:
    endpoint: localhost:6000
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
