dist:
  name: custom-otelcol
  desciption: custom otelcol with otlp receiver/exporter and file_storage extension
  output_path: ./custom-otelcol

receivers:
  - gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.95.0"

processors:
  - gomod: "go.opentelemetry.io/collector/processor/batchprocessor v0.95.0"
  - gomod: "go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.95.0"

exporters:
  - gomod: "go.opentelemetry.io/collector/exporter/otlpexporter v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.95.0"
  - gomod: "go.opentelemetry.io/collector/exporter/debugexporter v0.95.0"
  - gomod: "go.opentelemetry.io/collector/exporter/otlphttpexporter v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.95.0"

extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.95.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.95.0"
  - gomod: "go.opentelemetry.io/collector/extension/ballastextension v0.95.0"

