receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:

  otlp:
    endpoint: 192.168.101.128:4317
    tls:
      insecure: true
    sending_queue:
      storage: file_storage

  otlphttp:
    endpoint: http://192.168.101.128:4318
    tls:
      insecure: true
    headers:
      Content-type: application/json
    sending_queue:
      storage: file_storage
    encoding: json

  file/no_rotation_traces:
    path: /tmp/otelcol/file_exporter/traces.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true
  file/no_rotation_metrics:
    path: /tmp/otelcol/file_exporter/metrics.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true
  file/no_rotation_logs:
    path: /tmp/otelcol/file_exporter/logs.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800

extensions:
  file_storage:
    directory: /var/lib/otelcol 
    timeout: 1s
    compaction:
      on_start: true
      directory: /tmp/
      max_transaction_size: 65_536
    fsync: false
  health_check:
  memory_ballast:

service:
  extensions: [file_storage, health_check, memory_ballast]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlphttp, file/no_rotation_traces]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlphttp, file/no_rotation_metrics]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug, otlphttp, file/no_rotation_logs]

