receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:

  file/rotation_traces:
    path: /tmp/otelcol/file_exporter/deployment/traces.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true
  file/rotation_metrics:
    path: /tmp/otelcol/file_exporter/deployment/metrics.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true
  file/rotation_logs:
    path: /tmp/otelcol/file_exporter/deployment/logs.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file/rotation_traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file/rotation_metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file/rotation_logs]

