receivers:
  k8s_cluster:
  k8s_events:
  k8sobjects:

exporters:
  otlp:
    endpoint: 192.168.43.182:4317
    tls:
      insecure: true
    sending_queue:
      storage: file_storage

processors:
  batch:

extensions:
  file_storage:
    directory: /var/lib/otelcol
    timeout: 1s
    compaction:
      on_start: true
      directory: /tmp/
      max_transaction_size: 65_536
    fsync: false

service:
  extensions: [file_storage]
  pipelines:
    metrics:
      receivers: [k8s_cluster]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [k8s_cluster, k8s_events, k8sobjects]
      processors: [batch]
      exporters: [otlp]

