receivers:
  k8s_cluster:
  k8s_events:
  k8sobjects:

exporters:
  
  file/no_rotation_metrics:
    path: /tmp/otelcol/file_exporter/metrics.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true
  file/no_rotation_logs:
    path: /tmp/otelcol/file_exporter/logs.json
    rotation:
      max_megabytes: 1
      max_days: 1
      localtime: true

processors:
  batch:

extensions:
  file_storage:
    directory: /var/lib/otelcol
    timeout: 1s
    compaction:
      on_start: true
      directory: /tmp/
      max_transaction_size: 65_536
    fsync: false

service:
  extensions: [file_storage]
  pipelines:
    metrics:
      receivers: [k8s_cluster]
      processors: [batch]
      exporters: [file/no_rotation_metrics]
    logs:
      receivers: [k8s_cluster, k8s_events, k8sobjects]
      processors: [batch]
      exporters: [file/no_rotation_logs]

