receivers:
  k8s_cluster:
  k8s_events:
  k8sobjects:

exporters:
  otlp:
    endpoint: 192.168.43.182:4317
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [k8s_cluster]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [k8s_cluster, k8s_events, k8sobjects]
      processors: [batch]
      exporters: [otlp]

